<?php

/**
 * Commercial plan matrix — source of truth for seeders and entitlement UX.
 * Legacy codes (company_basic, store_pro, …) map onto these tiers.
 */
return [
    'currency' => env('PLAN_CURRENCY', 'SAR'),

    'meters' => [
        'ai_tokens' => ['overage' => 'hard_block', 'label' => 'رموز الذكاء الاصطناعي'],
        'ai_usage' => ['overage' => 'hard_block', 'label' => 'استخدام الذكاء الاصطناعي'],
        'whatsapp_messages' => ['overage' => 'hard_block', 'label' => 'رسائل واتساب'],
        'email_sends' => ['overage' => 'hard_block', 'label' => 'رسائل البريد'],
        'storage_mb' => ['overage' => 'upgrade_required', 'label' => 'التخزين'],
        'api_calls' => ['overage' => 'hard_block', 'label' => 'استدعاءات API'],
        'bookings' => ['overage' => 'upgrade_required', 'label' => 'الحجوزات'],
        'orders' => ['overage' => 'upgrade_required', 'label' => 'الطلبات'],
        'products' => ['overage' => 'upgrade_required', 'label' => 'المنتجات'],
        'customers' => ['overage' => 'upgrade_required', 'label' => 'العملاء'],
        'team_members' => ['overage' => 'upgrade_required', 'label' => 'أعضاء الفريق'],
        'users' => ['overage' => 'upgrade_required', 'label' => 'المستخدمون'],
        'domains' => ['overage' => 'upgrade_required', 'label' => 'النطاقات'],
        'websites' => ['overage' => 'upgrade_required', 'label' => 'المواقع'],
    ],

    'meter_aliases' => [
        'ai_tokens' => ['ai_usage'],
        'ai_usage' => ['ai_tokens'],
        'team_members' => ['users'],
        'users' => ['team_members'],
        'bookings' => ['bookings_per_month'],
        'bookings_per_month' => ['bookings'],
    ],

    'feature_matrix' => [
        'starter' => [
            'features' => [
                'dashboard', 'customers', 'appointments', 'public_booking',
                'website_builder', 'subscription', 'usage', 'conversations',
                'messages', 'smart_replies', 'ai', 'payments',
            ],
            'limits' => [
                'ai_usage' => 2000,
                'bookings' => 100,
                'customers' => 200,
                'team_members' => 3,
                'users' => 3,
                'websites' => 1,
                'domains' => 0,
                'products' => 50,
                'orders' => 100,
                'whatsapp_messages' => 0,
                'email_sends' => 200,
                'storage_mb' => 512,
                'api_calls' => 0,
            ],
        ],
        'pro' => [
            'features' => [
                'dashboard', 'customers', 'appointments', 'public_booking',
                'website_builder', 'custom_domains', 'subscription', 'usage',
                'conversations', 'messages', 'smart_replies', 'ai', 'payments',
                'payment_gateway', 'pos', 'qr_menu', 'finance', 'products',
                'categories', 'inventory', 'orders', 'email', 'analytics',
                'employees', 'whatsapp',
            ],
            'limits' => [
                'ai_usage' => 50000,
                'bookings' => 1000,
                'customers' => 2000,
                'team_members' => 15,
                'users' => 15,
                'websites' => 1,
                'domains' => 1,
                'products' => 1000,
                'orders' => 3000,
                'whatsapp_messages' => 1000,
                'email_sends' => 2000,
                'storage_mb' => 5120,
                'api_calls' => 0,
            ],
        ],
        'business' => [
            'features' => [
                'dashboard', 'customers', 'appointments', 'public_booking',
                'website_builder', 'custom_domains', 'subscription', 'usage',
                'conversations', 'messages', 'smart_replies', 'ai', 'payments',
                'payment_gateway', 'pos', 'qr_menu', 'finance', 'products',
                'categories', 'inventory', 'orders', 'email', 'analytics',
                'employees', 'whatsapp', 'roles_permissions', 'api', 'crm',
            ],
            'limits' => [
                'ai_usage' => 200000,
                'bookings' => 10000,
                'customers' => 20000,
                'team_members' => 50,
                'users' => 50,
                'websites' => 3,
                'domains' => 5,
                'products' => 10000,
                'orders' => 50000,
                'whatsapp_messages' => 10000,
                'email_sends' => 20000,
                'storage_mb' => 51200,
                'api_calls' => 50000,
            ],
        ],
        'enterprise' => [
            'features' => [
                'dashboard', 'customers', 'appointments', 'public_booking',
                'website_builder', 'custom_domains', 'subscription', 'usage',
                'conversations', 'messages', 'smart_replies', 'ai', 'payments',
                'payment_gateway', 'pos', 'qr_menu', 'finance', 'products',
                'categories', 'inventory', 'orders', 'email', 'analytics',
                'employees', 'whatsapp', 'roles_permissions', 'api', 'crm',
                'white_label', 'audit', 'feature_overrides',
            ],
            'limits' => [
                'ai_usage' => 1000000,
                'bookings' => 100000,
                'customers' => 200000,
                'team_members' => 200,
                'users' => 200,
                'websites' => 20,
                'domains' => 50,
                'products' => 100000,
                'orders' => 500000,
                'whatsapp_messages' => 100000,
                'email_sends' => 200000,
                'storage_mb' => 512000,
                'api_calls' => 500000,
            ],
        ],
    ],

    'comparison_rows' => [
        ['key' => 'appointments', 'label' => 'الحجوزات والمواعيد'],
        ['key' => 'website_builder', 'label' => 'الموقع الإلكتروني'],
        ['key' => 'custom_domains', 'label' => 'النطاق المخصص'],
        ['key' => 'ai', 'label' => 'الذكاء الاصطناعي'],
        ['key' => 'whatsapp', 'label' => 'واتساب'],
        ['key' => 'pos', 'label' => 'نقطة البيع'],
        ['key' => 'finance', 'label' => 'المالية والفواتير'],
        ['key' => 'email', 'label' => 'البريد الاحترافي'],
        ['key' => 'api', 'label' => 'واجهة البرمجة API'],
        ['key' => 'analytics', 'label' => 'التحليلات'],
        ['key' => 'crm', 'label' => 'إدارة العملاء المتقدمة'],
    ],
];
